# Generated by Django 3.2.9 on 2021-11-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='shop_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
